7-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 17:41:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema influencemeter_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `influencemeter_db` ;

-- -----------------------------------------------------
-- Schema influencemeter_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `influencemeter_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `influencemeter_db` ;

-- -----------------------------------------------------
-- Table `influencemeter_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`users` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `reset_senha` TINYINT NULL,
  `remember_token` VARCHAR(100) NULL,
  `avatar` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`throttles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`throttles` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`throttles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NULL,
  `is_default_password` TINYINT(4) NOT NULL,
  `last_access_at` TIMESTAMP NULL,
  `attempts` TINYINT(4) NULL,
  `suspended` TINYINT NULL,
  `last_attempt_at` TIMESTAMP NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_throttles_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_throttles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `influencemeter_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`users_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_roles_roles1_idx` (`role_id` ASC),
  INDEX `fk_users_has_roles_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `influencemeter_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `influencemeter_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`profiles` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`profiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `twitter_id` VARCHAR(75) NOT NULL,
  `screen_name` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `followers_count` INT unsigned,
  `friends_count` INT unsigned,
  `verified` TINYINT(2) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `engagement` FLOAT(10),
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `influencemeter_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`tweets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`tweets` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`tweets` (
  `id` INT unsigned NOT NULL AUTO_INCREMENT,
  `profile_id` INT unsigned NOT NULL,
  `id_str` VARCHAR(30) NOT NULL,
  `text` VARCHAR(400) NOT NULL,
  `followers_count` INT unsigned,
  `friends_count` INT unsigned,
  `favorite_count` INT unsigned,
  `retweet_count` INT unsigned,
  `retweet_status` TINYINT(2) unsigned,
  `reply` VARCHAR(30) NULL,
  `posted_at` VARCHAR(75) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `badalado` INT(2),
  `url` VARCHAR(150),
  PRIMARY KEY (`id`),
  INDEX `fk_tweets_profiles1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_tweets_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `influencemeter_db`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`hashtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`hashtags` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`hashtags` (
  `id` INT unsigned NOT NULL AUTO_INCREMENT,
  `profile_id` INT unsigned NOT NULL,
  `tweet_id` INT unsigned NOT NULL,
  `hashtag` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hashtags_profiles1_idx` (`profile_id` ASC),
  INDEX `fk_hashtags_tweets1_idx` (`tweet_id` ASC),
  CONSTRAINT `fk_hashtags_tweets1_idx`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `influencemeter_db`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hashtags_profiles1_idx`
    FOREIGN KEY (`profile_id`)
    REFERENCES `influencemeter_db`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`types_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`types_profile` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`types_profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(220) NULL,
  `recomendation` VARCHAR (500) NULL,
  `requisites` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`type_profile_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`type_profile_status` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`type_profile_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` INT UNSIGNED NOT NULL,
  `type_profile_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_type_profile_status_type_profile1_idx` (`type_profile_id` ASC),
  INDEX `fk_type_profile_status_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_type_profile_status_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `influencemeter_db`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_profile_status_type_profile1`
    FOREIGN KEY (`type_profile_id`)
    REFERENCES `influencemeter_db`.`types_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `influencemeter_db`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`loggers` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`loggers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NULL,
  `message` VARCHAR(200) NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loggers_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_loggers_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `influencemeter_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `influencemeter_db`.`types_engagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `influencemeter_db`.`types_engagement` ;

CREATE TABLE IF NOT EXISTS `influencemeter_db`.`types_engagement` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(75) NULL,
  `start_value` INT (255) unsigned NULL,
  `end_value` INT (255) unsigned NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -------------------------

INSERT INTO `roles` VALUES
(1, 'ROOT', 'Desenvolvedor'),
(2, 'ADMIN', 'Administrador do Sistema'),
(3, 'USUARIO', 'Usuário Comum');

INSERT INTO `users` VALUES
(1, 'Administrador', 'mayradbueno@gmail.com', '$2y$10$hravkHv4Whx6oXsw1jMwsOAovVvQ29vlTwVlLox1lgq9ZZUFOG6MO', 0,
'$2y$10$X/ri8NeCdc3oc2swndWwQ.uZSjDZFVMmaIS1/zQAMNg16cIaEbWJu', null, now(), null, null);

INSERT INTO `throttles` VALUES
(1, NULL, 0, NULL, 0, 0, NULL, 1);

INSERT INTO `users_roles` (`id`, `user_id`, `role_id`) VALUES
(1,1,1),(2,1,2),(3,1,3);

INSERT INTO `types_profile` VALUES
(
  1, 'INFLUENCIADOR',
  'Este perfil é comunicador e tem a capacidade de influenciar muitos outros usuários.',
  null,
  'Postagens próprias — não retweets — com alto engajamento. Ao menos 3 das 5 postagens mais badaladas não podem ser RT.'
),
(
  2, 'CAUSADOR',
  'Este perfil costuma responder e retweetar mais do que postar conteúdo próprio.',
  null,
  'Maiores taxas de engajamento estão em respostas e retweets. Das postagens mais badaladas, 3 ou mais são RT ou respostas.'
),
(
  3, 'ANIMAL POLÍTICO',
  'Este perfil usa a plataforma para dialogar com outros usuários.',
  null,
  'Cerca de 30% são respostas.'
),
(
  4, 'CASUAL',
  'Este perfil posta casualmente para uma audiência moderada ou pequena.',
  null,
  'Frequência baixa de postagens — menos de quatro vezes por semana — com engajamento moderado ou menor.'
),
(
  5, 'BISCOITEIRO',
  'Este perfil gosta de chamar a atenção com mídia (fotos e vídeos).',
  null,
  'Cerca de 40% das postagens contém fotos ou vídeos e/ou hashtags.'
),
(
  6, 'FEIRANTE',
  'Este perfil está tentando promover alguma coisa.',
  null,
  'Muitos seguidores, mas engajamento moderado ou baixo, links em 25% das postagens.'
),
(
  7, 'ADMIRÁVEL CHIP NOVO',
  '01000010 01101111 01110100 robô criado com propósitos provavelmente maliciosos.',
  null,
  'Não verificado, engajamento baixo, posta em intervalos regulares.'
),
(
  8, 'LAVOISIER',
  'Na natureza nada se cria... Este perfil usa muitos retweets.',
  null,
  'Mais de 30% de retweeted.'
);

INSERT INTO `types_engagement` (`id`, `description`, `start_value`, `end_value`) VALUES (
  1, 'Ínfimo', 49, 0
),
(
  2, 'Baixíssimo', 99, 50
),
(
  3, 'Baixo', 999, 100
),
(
  4, 'Moderado', 4999, 1000
),
(
  5, 'Alto', 9999, 5000
),
(
  6, 'Muito alto', 99999, 10000
),
(
  7, 'Altíssimo', 999999, 100000
),
(
  8, 'Estratosférico', 9999999, 1000000
);
